sudo: required
services:
    - docker

before_install:
    - docker build -t aalandril/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run aalandril/react-test npm test -- --coverage

after_success:
    - docker build -t aalandril/multi-client ./client
    - docker build -t aalandril/multi-nginx ./nginx
    - docker build -t aalandril/multi-server ./server
    - docker build -t aalandril/multi-worker ./worker